/* Teks antarmuka Vietnam — dibuat _kerja/buat_mini.py dari _kerja/mini/ui_vi.json */
window.VI_UI = {
"Audio speed": "Tốc độ âm thanh",
"Speed": "Tốc độ",
"Audio is not available for this sentence yet.": "Câu này chưa có âm thanh.",
"TBLL · 6 stages": "TBLL · 6 bước",
"Could not load the data. Run the app from a local server, e.g.": "Không tải được dữ liệu. Hãy chạy ứng dụng qua máy chủ cục bộ, ví dụ",
"Loading…": "Đang tải…",
"Could not load the data. Check your connection, then reload.": "Không tải được dữ liệu. Kiểm tra kết nối rồi tải lại trang.",
"Back": "Quay lại",
"Learn scene by scene, practise TOCFL-style questions, and track your own progress.": "Học theo từng tình huống, luyện câu hỏi kiểu TOCFL và tự theo dõi tiến bộ của mình.",
"Continue learning": "Tiếp tục học",
"stage {0} of 6": "bước {0}/6",
"Choose a volume": "Chọn tập",
"modules": "bài",
"words": "từ",
"grammar points": "điểm ngữ pháp",
"done": "xong",
"task average": "điểm nhiệm vụ trung bình",
"For your teacher": "Dành cho giáo viên",
"Send my results": "Gửi kết quả của tôi",
"Your scores & reflections go to your teacher": "Điểm và phần tự đánh giá của bạn được gửi cho giáo viên",
"Illustrations: Twemoji © Twitter/X &amp; contributors, licensed CC-BY 4.0. Black-and-white question images: OpenMoji (openmoji.org), licensed CC BY-SA 4.0.": "Hình minh họa: Twemoji © Twitter/X &amp; những người đóng góp, giấy phép CC-BY 4.0. Hình câu hỏi đen trắng: OpenMoji (openmoji.org), giấy phép CC BY-SA 4.0.",
"Modules": "Bài học",
"Vocabulary": "Từ vựng",
"Mock exam": "Thi thử",
"modules done": "bài đã xong",
"Goals": "Mục tiêu",
"Tasks": "Nhiệm vụ",
"Reflection": "Tự đánh giá",
"In the exam, audio can only be played {0}×.": "Trong bài thi, âm thanh chỉ được phát {0} lần.",
"played {0}×": "đã phát {0} lần",
"Play audio": "Phát âm thanh",
"Listen": "Nghe",
"tap to play": "chạm để phát",
"Transcript": "Lời thoại",
"Check answers": "Kiểm tra đáp án",
"Correct!": "Chính xác!",
"Not quite — here is why:": "Chưa đúng — đây là lý do:",
"Listen to the title": "Nghe tiêu đề",
"Module stages": "Các bước của bài",
"Finish": "Hoàn thành",
"Situation": "Tình huống",
"After this module, you can…": "Sau bài này, bạn có thể…",
"Why it matters for the exam": "Vì sao quan trọng cho kỳ thi",
"Your personal goal": "Mục tiêu của riêng bạn",
"E.g. I want to answer these questions without hesitating…": "Ví dụ: Tôi muốn trả lời được những câu hỏi này mà không do dự…",
"You can jump to any stage using the markers above.": "Bạn có thể chuyển đến bất kỳ bước nào bằng các mốc ở trên.",
"List": "Danh sách",
"Word practice": "Luyện từ",
"核心 · for active use": "核心 · dùng chủ động",
"補充 · recognise only": "補充 · chỉ cần nhận biết",
"Show pinyin": "Hiện pinyin",
"Same entry as:": "Cùng mục từ với:",
"not in the official TBCL list": "không có trong danh sách chính thức TBCL",
"from kosakata.xlsx": "từ kosakata.xlsx",
"TBCL Level {0} word · brought forward to this module": "Từ TBCL cấp {0} · được đưa lên bài này",
"Try to recall the meaning, then tap to check": "Hãy thử nhớ nghĩa, rồi chạm để kiểm tra",
"✓ Memorised": "✓ Đã thuộc",
"Mark as memorised": "Đánh dấu đã thuộc",
"Highlight new words": "Tô sáng từ mới",
"Tap a highlighted word to see its meaning. Tap a bubble to see the translation.": "Chạm vào từ được tô sáng để xem nghĩa. Chạm vào bong bóng để xem bản dịch.",
"Play": "Phát",
"Next line": "Câu tiếp theo",
"Show all": "Hiện tất cả",
"Fill in all the blanks first.": "Hãy điền hết các chỗ trống trước.",
"Next question ›": "Câu tiếp theo ›",
"See results ›": "Xem kết quả ›",
"You have mastered the tasks in this scene. Move on to grammar to tidy up the patterns.": "Bạn đã nắm vững các nhiệm vụ trong tình huống này. Hãy chuyển sang phần ngữ pháp để hệ thống lại các mẫu câu.",
"Almost! Reread the explanations for the questions you missed — the mistakes usually follow the same pattern.": "Gần đúng rồi! Đọc lại giải thích ở những câu chưa đúng — lỗi thường lặp lại theo cùng một kiểu.",
"Not yet — and that is normal on a first try. Go through the dialogue again, then retry. Your best score is kept.": "Chưa đạt — và điều đó bình thường ở lần đầu. Xem lại hội thoại rồi thử lại. Điểm cao nhất của bạn vẫn được lưu.",
"Attempt {0} · best score {1}%": "Lần thử {0} · điểm cao nhất {1}%",
"Try again": "Thử lại",
"Review answers": "Xem lại đáp án",
"No new pattern in this scene": "Tình huống này không có mẫu câu mới",
"This scene only adds vocabulary, on purpose. Patterns you reuse here:": "Tình huống này cố ý chỉ thêm từ vựng. Các mẫu câu bạn dùng lại ở đây:",
"You have already used these patterns in the dialogue & tasks. Now let us take the blocks apart.": "Bạn đã dùng các mẫu câu này trong hội thoại và nhiệm vụ. Bây giờ hãy tháo rời từng khối.",
"Pattern": "Mẫu câu",
"Quick check": "Kiểm tra nhanh",
"Not yet": "Chưa",
"Somewhat": "Tạm được",
"Confident": "Tự tin",
"Unit test · {0} TOCFL-style questions": "Kiểm tra cuối bài · {0} câu kiểu TOCFL",
"min": "phút",
"scored after you submit": "chấm điểm sau khi nộp",
"best": "cao nhất",
"Best task score": "Điểm nhiệm vụ cao nhất",
"Words memorised": "Từ đã thuộc",
"Goals confident": "Mục tiêu tự tin",
"The goal you wrote at the start": "Mục tiêu bạn viết lúc đầu",
"How confident are you now?": "Bây giờ bạn tự tin đến mức nào?",
"Which part is still difficult?": "Phần nào vẫn còn khó?",
"E.g. I still mix up 會 and 能 when listening…": "Ví dụ: Tôi vẫn nhầm 會 và 能 khi nghe…",
"My next steps": "Bước tiếp theo của tôi",
"Flashcards": "Thẻ ghi nhớ",
"See the word, recall its meaning, then flip the card. Be honest with yourself.": "Xem từ, nhớ nghĩa, rồi lật thẻ. Hãy trung thực với chính mình.",
"Listen → Meaning": "Nghe → Nghĩa",
"Sound only, no text — trains your ear like 聽力.": "Chỉ có âm thanh, không có chữ — luyện tai như 聽力.",
"Hanzi → Meaning": "Chữ Hán → Nghĩa",
"Recognise the written word without pinyin — like 閱讀.": "Nhận ra từ viết mà không có pinyin — như 閱讀.",
"Meaning → Hanzi": "Nghĩa → Chữ Hán",
"From English, choose the right hanzi.": "Từ nghĩa tiếng Việt, chọn chữ Hán đúng.",
"Opened": "Đã mở",
"All": "Tất cả",
"Hard words": "Từ khó",
"words practised": "từ đã luyện",
"mostly right": "thường đúng",
"hard words": "từ khó",
"Take words from modules…": "Lấy từ trong các bài…",
"Choose a practice mode · 10 words per session": "Chọn cách luyện · 10 từ mỗi lượt",
"Words you miss will come back more often until you get them right more often than wrong.": "Những từ bạn sai sẽ xuất hiện lại thường xuyên hơn cho đến khi bạn đúng nhiều hơn sai.",
"No words to practise yet.": "Chưa có từ để luyện.",
"Say this word and recall its meaning first.": "Hãy đọc từ này và nhớ nghĩa trước.",
"Got it": "Đã nhớ",
"Flip card": "Lật thẻ",
"tap to play again": "chạm để phát lại",
"Next ›": "Tiếp ›",
"Perfect! You recalled every word from memory.": "Tuyệt vời! Bạn đã nhớ được tất cả các từ.",
"Good. The words you missed have been noted and will come back more often.": "Tốt. Những từ bạn sai đã được ghi lại và sẽ xuất hiện thường xuyên hơn.",
"That is fine — the effort of recalling is exactly what strengthens memory. Go over the missed words now.": "Không sao — chính nỗ lực nhớ lại là điều giúp trí nhớ bền hơn. Hãy xem lại các từ sai ngay bây giờ.",
"To review": "Cần ôn lại",
"Retry the missed ones": "Làm lại các từ sai",
"New session": "Lượt mới",
"Done": "Xong",
"Just like the real exam": "Giống như kỳ thi thật",
"Exam in progress": "Bài thi đang làm dở",
"Continue · question": "Tiếp tục · câu",
"Short exam": "Bài thi ngắn",
"Long exam": "Bài thi dài",
"questions": "câu",
"Full exam · official format": "Thi đầy đủ · định dạng chính thức",
"<span lang=\"zh-TW\">聽力</span> 50 questions · 60 min, then <span lang=\"zh-TW\">閱讀</span> 50 questions · 60 min — the same number of questions per part as the TOCFL Band A paper": "<span lang=\"zh-TW\">聽力</span> 50 câu · 60 phút, sau đó <span lang=\"zh-TW\">閱讀</span> 50 câu · 60 phút — số câu mỗi phần giống đề TOCFL Band A",
"Question bank by part": "Ngân hàng câu hỏi theo phần",
"History": "Lịch sử",
"q.": "câu",
"Full exam": "Thi đầy đủ",
"Exam": "Bài thi",
"This unit has no unit test yet.": "Bài này chưa có bài kiểm tra cuối bài.",
"Unit test": "Kiểm tra cuối bài",
"Q": "Câu",
"Previous": "Trước",
"Next": "Tiếp",
"Finish 聽力": "Xong 聽力",
"Submit": "Nộp bài",
"Questions": "Câu",
"audio max.": "âm thanh tối đa",
"The timer ({0} min{1}) starts when you press Start.": "Đồng hồ ({0} phút{1}) bắt đầu chạy khi bạn nhấn Bắt đầu.",
"Continue": "Tiếp tục",
"Start": "Bắt đầu",
"聽力 time is up — moving on to 閱讀.": "Hết giờ 聽力 — chuyển sang 閱讀.",
"Time is up — your answers have been submitted.": "Hết giờ — bài làm của bạn đã được nộp.",
"{0} question(s) still unanswered. Submit now?": "Còn {0} câu chưa trả lời. Nộp bài ngay?",
"Results": "Kết quả",
"Time used: {0} min {1} s.": "Thời gian đã dùng: {0} phút {1} giây.",
"By part": "Theo từng phần",
"In 閱讀 Part 4, each blank counts as one point, just like in the official exam.": "Ở 閱讀 Part 4, mỗi chỗ trống được tính một điểm, giống như kỳ thi chính thức.",
"Modules to review": "Bài cần ôn lại",
"Review questions": "Xem lại câu hỏi",
"Wrong only": "Chỉ câu sai",
"No wrong answers.": "Không có câu sai.",
"Retake test": "Làm lại bài kiểm tra",
"New exam": "Bài thi mới",
"Trial module · level {0} · 6 units": "Học liệu thử nghiệm · cấp {0} · 6 bài",
"Trial module for TOCFL Band A preparation.": "Học liệu thử nghiệm luyện thi TOCFL Band A.",
"1 · About you & your level": "1 · Thông tin của bạn & cấp độ",
"± 3 min": "± 3 phút",
"2 · Questionnaire (before)": "2 · Bảng hỏi (trước)",
"20 statements about exam anxiety · ± 5 min": "20 câu về lo âu khi thi · ± 5 phút",
"3 · Pre-test": "3 · Bài kiểm tra đầu vào",
"20 TOCFL-style questions · 30 min": "20 câu kiểu TOCFL · 30 phút",
"4 · Learn the 6 units": "4 · Học 6 bài",
"The units open after the pre-test.": "Các bài sẽ mở sau bài kiểm tra đầu vào.",
"Finish all six stages of each unit, including the tasks. The unit test is in the last stage.": "Hoàn thành cả sáu bước của mỗi bài, kể cả phần nhiệm vụ. Bài kiểm tra cuối bài nằm ở bước cuối cùng.",
"5 · Questionnaire (after)": "5 · Bảng hỏi (sau)",
"The same 20 statements · ± 5 min": "20 câu giống như trước · ± 5 phút",
"6 · Post-test": "6 · Bài kiểm tra cuối",
"7 · Your opinion of the module": "7 · Ý kiến của bạn về học liệu",
"10 statements + 3 short questions": "10 câu + 3 câu hỏi ngắn",
"Finished — thank you!": "Đã hoàn thành — cảm ơn bạn!",
"Sending status": "Trạng thái gửi",
"Last sent": "Lần gửi gần nhất",
"Not sent yet": "Chưa gửi",
"Indonesia": "Indonesia",
"Vietnam": "Việt Nam",
"Other": "Khác",
"Yes": "Có",
"No": "Không",
"< 6 months": "< 6 tháng",
"6–12 months": "6–12 tháng",
"1–2 years": "1–2 năm",
"> 2 years": "> 2 năm",
"Within 3 months": "Trong vòng 3 tháng",
"In 3–6 months": "Sau 3–6 tháng",
"In more than 6 months": "Sau hơn 6 tháng",
"Not sure yet": "Chưa chắc",
"About you": "Thông tin của bạn",
"About this trial": "Về đợt thử nghiệm này",
"This module is part of a thesis study on how learning materials can reduce TOCFL exam anxiety. You will fill in a questionnaire and a short test before and after studying 6 units. Your answers are only used for research; your name is not published.": "Học liệu này là một phần của nghiên cứu luận văn về việc tài liệu học tập có thể giảm lo âu khi thi TOCFL như thế nào. Bạn sẽ làm một bảng hỏi và một bài kiểm tra ngắn trước và sau khi học 6 bài. Câu trả lời của bạn chỉ dùng cho nghiên cứu; tên của bạn sẽ không được công bố.",
"Name or initials": "Họ tên hoặc chữ viết tắt",
"Age": "Tuổi",
"Nationality": "Quốc tịch",
"Your current Chinese level (self-assessment)": "Trình độ tiếng Trung hiện tại (tự đánh giá)",
"Have you ever taken a Chinese proficiency test (TOCFL)?": "Bạn đã từng thi năng lực tiếng Trung (TOCFL) chưa?",
"How long have you studied Chinese?": "Bạn đã học tiếng Trung bao lâu?",
"When do you plan to take the TOCFL?": "Khi nào bạn dự định thi TOCFL?",
"Choose the level you will study in this trial": "Chọn cấp độ bạn sẽ học trong đợt thử nghiệm này",
"Not sure? Choose the level where most of the descriptions fit you. The level cannot be changed after the first questionnaire.": "Chưa chắc? Hãy chọn cấp độ có phần mô tả phù hợp với bạn nhất. Không thể đổi cấp độ sau bảng hỏi đầu tiên.",
"I agree to take part, and that my answers, scores and progress in this app are sent to the researcher.": "Tôi đồng ý tham gia, và đồng ý để câu trả lời, điểm số và tiến độ của tôi trong ứng dụng này được gửi cho người nghiên cứu.",
"Save and continue": "Lưu và tiếp tục",
"Enter your name or initials.": "Hãy nhập họ tên hoặc chữ viết tắt.",
"Please answer all the questions.": "Hãy trả lời tất cả các câu hỏi.",
"Choose a level.": "Hãy chọn một cấp độ.",
"Tick the consent box first.": "Hãy đánh dấu ô đồng ý trước.",
"Questionnaire (before)": "Bảng hỏi (trước)",
"Questionnaire (after)": "Bảng hỏi (sau)",
"Read each statement and choose how much you agree. There are no right or wrong answers — answer honestly about how you feel about the TOCFL exam.": "Đọc từng câu và chọn mức độ bạn đồng ý. Không có câu trả lời đúng hay sai — hãy trả lời thật lòng về cảm nhận của bạn đối với kỳ thi TOCFL.",
"Save": "Lưu",
"Statement {0} is not answered yet.": "Câu {0} chưa được trả lời.",
"Pre-test": "Bài kiểm tra đầu vào",
"Post-test": "Bài kiểm tra cuối",
"Thank you! The units are now open. This score is only your starting point — it will be compared with the post-test.": "Cảm ơn bạn! Các bài học đã được mở. Điểm này chỉ là điểm xuất phát của bạn — sẽ được so sánh với bài kiểm tra cuối.",
"Pre-test {0}% → post-test {1}%. One last step: tell us what you think of the module.": "Đầu vào {0}% → cuối {1}%. Bước cuối cùng: hãy cho chúng tôi biết bạn nghĩ gì về học liệu.",
"Your opinion": "Ý kiến của bạn",
"Short questions (optional)": "Câu hỏi ngắn (có thể bỏ trống)",
"How much do you agree with these statements about the module?": "Bạn đồng ý đến mức nào với những nhận định sau về học liệu?",
"You have finished the whole trial. Thank you very much for taking part! 謝謝！": "Bạn đã hoàn thành toàn bộ đợt thử nghiệm. Cảm ơn bạn rất nhiều vì đã tham gia! 謝謝！",
"Anxiety score (20 = calm, 100 = very anxious): {0} → {1}": "Điểm lo âu (20 = bình tĩnh, 100 = rất lo âu): {0} → {1}",
"Sending to the researcher": "Gửi cho người nghiên cứu",
"Not sent yet.": "Chưa gửi.",
"The last attempt failed — check your internet connection and press the button below.": "Lần gửi gần nhất bị lỗi — hãy kiểm tra kết nối internet rồi nhấn nút bên dưới.",
"Your results are sent automatically after each step. You can also send them again here — the old data is updated, not duplicated.": "Kết quả của bạn được gửi tự động sau mỗi bước. Bạn cũng có thể gửi lại ở đây — dữ liệu cũ sẽ được cập nhật, không bị trùng.",
"Participant code": "Mã người tham gia",
"Send results now": "Gửi kết quả ngay",
"Sending…": "Đang gửi…",
"Results sent. 謝謝！": "Đã gửi kết quả. 謝謝！",
"Sending failed. Check your internet connection, then try again.": "Gửi thất bại. Kiểm tra kết nối internet rồi thử lại.",
"Supporting words from other units · {0}": "Từ hỗ trợ từ các bài khác · {0}",
"These words appear in this unit but were taught in units that are not part of this trial. You do not need to memorise them — tap a word to hear it.": "Những từ này xuất hiện trong bài này nhưng được dạy ở các bài không thuộc đợt thử nghiệm. Bạn không cần học thuộc — chạm vào từ để nghe.",
"Do the tasks (stage 4) first.": "Hãy làm phần nhiệm vụ (bước 4) trước.",
"Picture description": "Mô tả tranh",
"Question & answer": "Hỏi & đáp",
"Dialogue": "Hội thoại",
"Implied meaning": "Ý ngầm",
"Sentence → picture": "Câu → tranh",
"Picture → sentence": "Tranh → câu",
"Gap fill with picture": "Điền từ theo tranh",
"Paragraph completion": "Hoàn thành đoạn văn",
"Reading comprehension": "Đọc hiểu",
"Look at the picture, listen to the question and three answers (A–C), then choose the one that matches the picture.": "Xem tranh, nghe câu hỏi và ba đáp án (A–C), rồi chọn đáp án khớp với tranh.",
"Listen to a short exchange and choose the right picture or response.": "Nghe một đoạn hỏi–đáp ngắn và chọn tranh hoặc câu đáp đúng.",
"Listen to a dialogue of several turns and the question.": "Nghe một đoạn hội thoại nhiều lượt và câu hỏi.",
"Listen to the dialogue and catch what is meant but not said directly. Choose A–D.": "Nghe hội thoại và nắm được ý không nói thẳng ra. Chọn A–D.",
"Read one sentence and choose the matching picture.": "Đọc một câu và chọn bức tranh phù hợp.",
"Look at the picture and choose the matching sentence.": "Xem tranh và chọn câu phù hợp.",
"Look at the picture and choose the right word for the blank.": "Xem tranh và chọn từ đúng cho chỗ trống.",
"Fill in the blanks in the paragraph. Each option can be used only once; some options are not used.": "Điền vào các chỗ trống trong đoạn văn. Mỗi lựa chọn chỉ dùng một lần; có lựa chọn không được dùng.",
"Read a short text and choose answer A–D.": "Đọc một đoạn văn ngắn và chọn đáp án A–D.",
"Replay the dialogue and listen": "Nghe lại hội thoại",
"Practise the 核心 words with audio": "Luyện các từ 核心 có âm thanh",
"Redo the tasks": "Làm lại các nhiệm vụ",
"Move on to the next module": "Chuyển sang bài tiếp theo",
"Admin password": "Mật khẩu quản trị",
"Wrong password.": "Sai mật khẩu.",
"This device already has participant data. Admin mode will replace it. Continue?": "Thiết bị này đã có dữ liệu của người tham gia. Chế độ quản trị sẽ thay thế dữ liệu đó. Tiếp tục?",
"Leave admin mode? All admin answers and unit progress on this device will be deleted.": "Thoát chế độ quản trị? Mọi câu trả lời của quản trị viên và tiến độ các bài trên thiết bị này sẽ bị xóa.",
"Delete the admin answers (questionnaires, tests, evaluation)?": "Xóa câu trả lời của quản trị viên (bảng hỏi, bài kiểm tra, đánh giá)?",
"Admin mode": "Chế độ quản trị",
"Every step is open in any order. Nothing is sent to the researcher.": "Mọi bước đều mở, theo thứ tự tùy ý. Không có dữ liệu nào được gửi cho nhà nghiên cứu.",
"Level": "Cấp độ",
"Questionnaire version": "Phiên bản bảng hỏi",
"Has taken TOCFL": "Đã từng thi TOCFL",
"Never taken TOCFL": "Chưa từng thi TOCFL",
"Clear answers": "Xóa câu trả lời",
"Leave admin mode": "Thoát quản trị",
"Admin mode: nothing is sent.": "Chế độ quản trị: không gửi dữ liệu.",
"Enter admin mode": "Vào chế độ quản trị",
"Open every step without filling in the forms (for checking only)": "Mở mọi bước mà không cần điền biểu mẫu (chỉ để kiểm tra)",
"audio plays 2× automatically (one tap)": "âm thanh tự phát 2 lần (bấm một lần)",
"The audio has already been played (2× automatically) and cannot be repeated.": "Âm thanh đã được phát (tự động 2 lần) và không thể phát lại.",
"played 2×": "đã phát 2 lần",
"playing {0}/2": "đang phát {0}/2",
"Notes from the grammar book": "Ghi chú từ sách ngữ pháp",
"Source": "Nguồn",
"More practice": "Luyện tập thêm",
"Start level {0}? You will do a new pre-test, 6 units, post-test and questionnaires for {1}. Your {2} results are already saved and sent.": "Bắt đầu cấp độ {0}? Bạn sẽ làm bài kiểm tra đầu vào mới, 6 bài, bài kiểm tra cuối và các bảng hỏi cho {1}. Kết quả {2} của bạn đã được lưu và gửi.",
"Optional": "Tùy chọn",
"Continue to level {0}": "Tiếp tục lên cấp độ {0}",
"You have finished {0}. Want to go on? New pre-test, 6 units of {1} and post-test.": "Bạn đã hoàn thành {0}. Muốn học tiếp không? Bài kiểm tra đầu vào mới, 6 bài {1} và bài kiểm tra cuối.",
"round": "vòng",
"Not passed yet / Novice (準備級)": "Chưa đỗ / Novice (準備級)",
"A2 · 基礎級 or higher": "A2 · 基礎級 trở lên",
"Highest TOCFL level you have passed": "Cấp độ TOCFL cao nhất bạn đã đỗ",
"Your starting level in this trial": "Cấp độ bắt đầu của bạn trong thử nghiệm này",
"You have already passed A2 or higher. This trial module only covers levels A0–A2, so it is not meant for you. Thank you for your interest! 謝謝！": "Bạn đã đỗ A2 trở lên. Học phần thử nghiệm này chỉ gồm cấp độ A0–A2 nên không dành cho bạn. Cảm ơn bạn đã quan tâm! 謝謝！",
"Answer the questions above first.": "Hãy trả lời các câu hỏi ở trên trước.",
"The level is set automatically: if you passed TOCFL A1, you start at A2; otherwise you start at the level of your self-assessment. After finishing, you may continue to the next level (up to A2). The level cannot be changed after the first questionnaire.": "Cấp độ được xác định tự động: nếu bạn đã đỗ TOCFL A1, bạn bắt đầu ở A2; nếu chưa, bạn bắt đầu ở cấp độ bạn tự đánh giá. Sau khi hoàn thành, bạn có thể học tiếp cấp độ tiếp theo (đến A2). Không thể đổi cấp độ sau bảng hỏi đầu tiên.",
"This trial only covers A0–A2.": "Thử nghiệm này chỉ dành cho A0–A2.",
"Answer all the questions.": "Hãy trả lời tất cả các câu hỏi."
};
